minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: TRUE

  image: stealthii/minecraft-server

  container_name: minecraft-server

  tty: true
  stdin_open: true
  restart: always
